### ISSUE TITLE
How can you style the look of the ResizableRect?

### ISSUE THREAD

**Issue by tomsoderlund** [mockingbot/react-resizable-rotatable-draggable#2]
Change border color, cursors etc?

**Comment by WeiWang120** [comment]
document.querySelector('.rect').style.borderColor = 'blue'
or you can use css selectors

**Comment by WeiWang120** [comment]
> Change border color, cursors etc?

document.querySelector('.rect').style.borderColor = 'blue'
or you can use css selectors
