### ISSUE TITLE
How to add child elements to ResizableRect ?

### ISSUE THREAD

**Issue by MistrySaurabh** [mockingbot/react-resizable-rotatable-draggable#3]
I want to display an element inside ResizableRect , and drag-drop resize facility to that child element ....how to do that ?

here what i have tried , but it is only showing rectangle , not button inside it.
  ```
<ResizableRect 
      ...
>
     <button className="btn btn-primary">Button</button>
</ResizableRect>
```

**Comment by WeiWang120** [comment]
I'm assuming you want to drag-drop and resize the button, right?
So what you need to do is passing left, top, width and height of this button to the component, and for every handle function(e.g. handleResize) will return a corresponding value, the apply this value to your button. Hope that helps!

**Comment by ByronMorley** [comment]
I am stuck doing on the same thing, Would you be able to provide an quick example on this please ?

**Comment by WeiWang120** [comment]
> I am stuck doing on the same thing, Would you be able to provide an quick example on this please ?

```javascript
import React, { Component } from 'react'
import ResizableRect from 'react-resizable-rotatable-draggable'

class App extends Component {
  constructor() {
    super()
    this.state = {
      width: 100,
      height: 100,
      top: 100,
      left: 100,
      rotateAngle: 0
    }
  }

  handleResize = (style, isShiftKey, type) => {
    // type is a string and it shows which resize-handler you clicked
    // e.g. if you clicked top-right handler, then type is 'tr'
    let { top, left, width, height } = style
    top = Math.round(top)
    left = Math.round(left)
    width = Math.round(width)
    height = Math.round(height)
    this.setState({
      top,
      left,
      width,
      height
    })
  }

  handleRotate = (rotateAngle) => {
    this.setState({
      rotateAngle
    })
  }

  handleDrag = (deltaX, deltaY) => {
    this.setState({
      left: this.state.left + deltaX,
      top: this.state.top + deltaY
    })
  }

  render() {
    const {width, top, left, height, rotateAngle} = this.state
    const buttonStyle = { width, height, top, left, transfrom: `rotate(${rotateAngle}deg)`, position: 'absolute' }
    return (
      <div className="App">
        <button style={buttonStyle} />
        <ResizableRect
          left={left}
          top={top}
          width={width}
          height={height}
          rotateAngle={rotateAngle}
          // aspectRatio={false}
          // minWidth={10}
          // minHeight={10}
          zoomable='n, w, s, e, nw, ne, se, sw'
          // rotatable={true}
          // onRotateStart={this.handleRotateStart}
          onRotate={this.handleRotate}
          // onRotateEnd={this.handleRotateEnd}
          // onResizeStart={this.handleResizeStart}
          onResize={this.handleResize}
          // onResizeEnd={this.handleUp}
          // onDragStart={this.handleDragStart}
          onDrag={this.handleDrag}
          // onDragEnd={this.handleDragEnd}
        />
      </div>
    )
  }
}

export default App
```

Notice the only difference between this code and usage in the documentation is I added a `button` tag
in the `div.App`, and I apply the style in the state to this button, so that the button will always behaves the same way as the resizer does

**Comment by MistrySaurabh** [comment]
> > I am stuck doing on the same thing, Would you be able to provide an quick example on this please ?
> 
> ```js
> import React, { Component } from 'react'
> import ResizableRect from 'react-resizable-rotatable-draggable'
> 
> class App extends Component {
>   constructor() {
>     super()
>     this.state = {
>       width: 100,
>       height: 100,
>       top: 100,
>       left: 100,
>       rotateAngle: 0
>     }
>   }
> 
>   handleResize = (style, isShiftKey, type) => {
>     // type is a string and it shows which resize-handler you clicked
>     // e.g. if you clicked top-right handler, then type is 'tr'
>     let { top, left, width, height } = style
>     top = Math.round(top)
>     left = Math.round(left)
>     width = Math.round(width)
>     height = Math.round(height)
>     this.setState({
>       top,
>       left,
>       width,
>       height
>     })
>   }
> 
>   handleRotate = (rotateAngle) => {
>     this.setState({
>       rotateAngle
>     })
>   }
> 
>   handleDrag = (deltaX, deltaY) => {
>     this.setState({
>       left: this.state.left + deltaX,
>       top: this.state.top + deltaY
>     })
>   }
> 
>   render() {
>     const {width, top, left, height, rotateAngle} = this.state
>     const buttonStyle = { width, height, top, left, transfrom: `rotate(${rotateAngle}deg)`, position: 'absolute' }
>     return (
>       <div className="App">
>         <button style={buttonStyle} />
>         <ResizableRect
>           left={left}
>           top={top}
>           width={width}
>           height={height}
>           rotateAngle={rotateAngle}
>           // aspectRatio={false}
>           // minWidth={10}
>           // minHeight={10}
>           zoomable='n, w, s, e, nw, ne, se, sw'
>           // rotatable={true}
>           // onRotateStart={this.handleRotateStart}
>           onRotate={this.handleRotate}
>           // onRotateEnd={this.handleRotateEnd}
>           // onResizeStart={this.handleResizeStart}
>           onResize={this.handleResize}
>           // onResizeEnd={this.handleUp}
>           // onDragStart={this.handleDragStart}
>           onDrag={this.handleDrag}
>           // onDragEnd={this.handleDragEnd}
>         />
>       </div>
>     )
>   }
> }
> 
> export default App
> ```
> 
> Notice the only difference between this code and usage in the documentation is I added a `button` tag
> in the `div.App`, and I apply the style in the state to this button, so that the button will always behaves the same way as the resizer does

Resize proper working , but rotate not working with this code 
<img width="314" alt="screen shot 2018-10-10 at 18 44 48" src="https://user-images.githubusercontent.com/16002832/46738826-c5d83900-ccbc-11e8-8ebf-92d0cd99daf1.png">

**Comment by WeiWang120** [comment]
oops, I made a typo in the buttonStyle, it should be `transform` instead of `transfrom`.

**Comment by MistrySaurabh** [comment]
Hey @WeiWang120 ,  I have tried a different way by passing child element to your components , in ResizableRect component 

```
<ResizableRect
 ...
>
{this.props.children}
</ResizableRect> 
```

and inside index.js for StyledRect

```
<StyledRect
...
>
{this.props.children}
</StyledRect>
```

by doing this , i am able to use it like below : 

  ```
<ResizableRect
    . . .
 >
   <button  style={{ height:height,width:width }} className="btn btn-primary">My Button</button>
  </ResizableRect>  
```

Now I want to use multiple ResizableRect component for different elements like below 
<img width="564" alt="screen shot 2018-10-12 at 12 34 04" src="https://user-images.githubusercontent.com/16002832/46853749-9c362380-ce1c-11e8-8a22-30486d317c75.png">


```
import React, { Component } from 'react';
import ResizableRect from './ResizableRect';
import {findIndex} from 'lodash'

class App extends Component {
  constructor() {
    super()
    this.state = {
      layers:[{
        id:1,
        width: 100,
        height: 100,
        top: 100,
        left: 100,
        rotateAngle: 0,
      },{
        id:2,
        width: 200,
        height: 200,
        top: 280,
        left: 200,
        rotateAngle: 45,
      }]
    }
    
  }

  handleResize = (style, isShiftKey, type) => {
    // type is a string and it shows which resize-handler you clicked
    // e.g. if you clicked top-right handler, then type is 'tr'
  
    let { top, left, width, height } = style
    top = Math.round(top)
    left = Math.round(left)
    width = Math.round(width)
    height = Math.round(height)
    console.log('top ==',top);
    // let layers=[...this.state.layers]
   // let index= findIndex(layers, function(o) { return o.id =layer.id; });
   // let currentLayer=layers[index];
   // console.log(currentLayer);
   /*  currentLayer.top=top
    currentLayer.left=left
    currentLayer.width=width
    currentLayer.height=height
    layers[index]=currentLayer
    this.setState({
       layers:layers
    })    */
  }

  handleRotate = (e,rotateAngle) => {
    console.log(e,rotateAngle)
    /* this.setState({
      rotateAngle
    }) */
  }

  handleDrag = (layer,deltaX, deltaY) => {
   /*  this.setState({
      left: this.state.left + deltaX,
      top: this.state.top + deltaY
    }) */
  }

  handleClick=()=>{

  }

  handleHover=()=>{

  }

  render() {
    //const {width, top, left, height, rotateAngle} = this.state
    //const buttonStyle = { width, height, top, left, transform: `rotate(${rotateAngle}deg)`, position: 'absolute' }

    return (
      <div className="App">
        {
          this.state.layers.map((layer,index) => (
            <ResizableRect
            key={index}
            id={layer.id}
            onClick={this.handleClick}
            onHover={this.handleHover}
            left={layer.left}
            top={layer.top}
            width={layer.width}
            height={layer.height}
            rotateAngle={layer.rotateAngle}
            // aspectRatio={false}
            // minWidth={10}
            // minHeight={10}
            zoomable='n, w, s, e, nw, ne, se, sw'
            // rotatable={true}
            // onRotateStart={this.handleRotateStart}
            onRotate={this.handleRotate}
            // onRotateEnd={this.handleRotateEnd}
            // onResizeStart={this.handleResizeStart}
            onResize={this.handleResize}
            // onResizeEnd={this.handleUp}
            // onDragStart={this.handleDragStart}
            onDrag={this.handleDrag}
            // onDragEnd={this.handleDragEnd}
          >
          <button style={{ height:layer.height,width:layer.width }} className="btn btn-primary">My Button</button>
          </ResizableRect>
          ))
      }
      </div>
    )
  }
}

export default App;
```

but I am unable to resize , rotate , drag-drop ....
I have to pass current layer from map loop to ResizableRect component's handleRotate , handleResize , handleDrag method , but if i add one extra parameter in these methods ....methods defined in ResizableRect component not working ,

so how can i use multiple ResizableRect component , please help me .

**Comment by ozgrozer** [comment]
I've made a simple React component with hooks to add a child element into the ResizableRect.

https://codesandbox.io/s/5zk612nvk4
