### ISSUE TITLE
TypeError: Cannot read property 'getBoundingClientRect' of undefined

### ISSUE THREAD

**Issue by MistrySaurabh** [mockingbot/react-resizable-rotatable-draggable#5]
I have created sample app using create-react-app , and copied your code from src and paste it . 
resize and drag drop is working proper but , I got below error on Rotate : 
<img width="1063" alt="screen shot 2018-10-16 at 14 26 39" src="https://user-images.githubusercontent.com/16002832/47004812-fa7e4180-d14f-11e8-9220-0a0efd6db861.png">

  package.json versions : 

  ```
 "prop-types": "^15.6.2",
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "react-scripts": "2.0.5",
    "styled-components": "^4.0.0"

```

It is working in  "react-scripts": "2.0.3", but as i changed   "react-scripts": "2.0.5", it gives me error

**Comment by iny7** [comment]
Hi, I noticed that you import `styled-components@4` in this demo, which was released several days ago and took some break changes. Please check [this migration list](https://www.styled-components.com/docs/faqs#what-do-i-need-to-do-to-migrate-to-v4) if you have to copy source code into personal project, or just use `styled-components@3.x`
